# ~/.config/starship.toml
add_newline = true

format = """
$directory$git_branch$git_status$nodejs$python$terraform$aws
$character"""

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = "([$all_status$ahead_behind]($style) )"

[nodejs]
format = "[$symbol($version )]($style)"

[python]
format = "[$symbol($version )(\\($virtualenv\\) )]($style)"

[terraform]
format = "[$symbol$workspace]($style) "

[aws]
format = "[$symbol($profile )(\\($region\\) )]($style)"
symbol = "aws "

[cmd_duration]
min_time = 2000
